---
- name: Download cloudwatch monitoring scripts
  get_url: url={{cw_script_download_url}} dest=/tmp/CloudWatchMonitoringScripts.zip

- name: Install unzip
  package: name=unzip state=present

- name: Create install directory
  file: path={{cw_install_dir}} state=directory

- name: Unzip the scripts
  command: unzip -ju /tmp/CloudWatchMonitoringScripts.zip -d {{cw_install_dir}}
